# (c) Copyright 2021 Hewlett Packard Enterprise Development LP

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msdev2test-abcde-07699de9-infra
spec:
  destination:
    namespace: infra
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://harbor.gl-hpe.local/chartrepo/library'
    chart: 'msdev2test-abcde-07699de9-infra'
    targetRevision: '*'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

